language: node_js
sudo: false
dist: trusty

node_js:
  - '8'

addons:
  chrome: stable

jobs:
  include:
    - env: "PHASE=lint"
    - env: "PHASE=unit"
    - env: "PHASE=aot"
    - env: "PHASE=lib_build"
    - stage: GitHub Release
      env: "PHASE=demo_deploy"
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: dist

install:
  - npm install

script:
  - ./scripts/travis-script.sh

cache:
  directories:
    - ./node_modules/
